TextRpg_MonsterHunting/Character.cs
=> [Init] Character 클래스 생성

TextRpg_MonsterHunting/Character.cs, TextRpg_MonsterHunting/TextRpg_MonsterHunting.sln
=> [Init] Feature character

TextRpg_MonsterHunting/Game.cs, TextRpg_MonsterHunting/Program.cs, TextRpg_MonsterHunting/TextRpg_MonsterHunting.sln, TextRpg_MonsterHunting/Utils.cs
Game 기능 :
게임 시작, 게임 진행 최상위 루프 구현
Utils는 그냥 추가만 해둠
=>  [Add] Game, Utils 파일 추가 및 Game 구현

TextRpg_MonsterHunting/Character.cs
=> [Chore] 직업 자료형이름 변경

TextRpg_MonsterHunting/Character.cs
=> [Chore] 생성자 수정

TextRpg_MonsterHunting/Character.cs, TextRpg_MonsterHunting/Game.cs, TextRpg_MonsterHunting/Item.cs, TextRpg_MonsterHunting/Utils.cs
=> [Rename] Item 에 enum 타입명들 수정

TextRpg_MonsterHunting/Inventory.cs, TextRpg_MonsterHunting/Item.cs, TextRpg_MonsterHunting/Utils.cs
Utils에 List<Item> 대체할 클래스 추가(json용)
인벤토리에 인벤토리 창 들어가는 기능 추가
이제 장착장비 관리창 만들 예정
=> [Feature][Add] 유틸, 인벤토리 기능 추가

TextRpg_MonsterHunting/Inventory.cs, TextRpg_MonsterHunting/Item.cs, TextRpg_MonsterHunting/Utils.cs
list 대체 클래스에 [index]로 해당 값 가져오거나 수정하게 변경
=> [Update] utils에 list 대체 클래스 수정

TextRpg_MonsterHunting/Game.cs, TextRpg_MonsterHunting/Inventory.cs, TextRpg_MonsterHunting/Item.cs
=> [Feature][Update] 인벤토리 기능 수정 및 추가

TextRpg_MonsterHunting/Character.cs, TextRpg_MonsterHunting/Utils.cs
=> [Update] 일반 공격 메소드 수정

TextRpg_MonsterHunting/Dungeon.cs
=> Feature dungeon

TextRpg_MonsterHunting/Character.cs, TextRpg_MonsterHunting/SkillManager.cs
- 직업 클래스를 생성하여 각 직업에 맞는 스킬 초기화
- 스킬매니저에서 스킬 추가, 스킬 목록 출력, 번호에 해당하는 스킬 사용 구조 변경함
=> [Update] 스킬 매니저 추가, 직업 클래스 추가

TextRpg_MonsterHunting/Dungeon.cs
=> [Chore]코드 오류난부분 주석으로 변경

TextRpg_MonsterHunting/Character.cs, TextRpg_MonsterHunting/Monster.cs, TextRpg_MonsterHunting/Utils.cs
Humanoid 인터페이스 추가
해당 인터페이스를 캐릭터와 몬스터가 상속
몬스터에 체력감소, 공격력 계산 함수 추가
몇개의 몬스터 변수 명 인터페이스에 맞춰서 캐릭터랑 같게 변경
=> [Feature][Add] Humanoid 인터페이스 추가

TextRpg_MonsterHunting/Dungeon.cs
=> [Chore]던젼 괄호수정 완료

TextRpg_MonsterHunting/Game.cs, TextRpg_MonsterHunting/Inventory.cs, TextRpg_MonsterHunting/Scene/DungeonStageScene.cs, TextRpg_MonsterHunting/Scene/EquipmentScene.cs, TextRpg_MonsterHunting/Scene/IntroScene.cs, TextRpg_MonsterHunting/Scene/InventoryScene.cs, TextRpg_MonsterHunting/Scene/Scene.cs, TextRpg_MonsterHunting/Scene/SceneManager.cs, TextRpg_MonsterHunting/Scene/StartScene.cs, TextRpg_MonsterHunting/UI.cs
- 각 Scene 부르기 편하게 SceneManager 추가(싱글톤)하여 관리하도록 수정
- Game 클래스 코드 정리
- UI 클래스 CountdownComment() 메소드 생성
=> [Feature] SceneManager 추가

TextRpg_MonsterHunting/Character/Character.cs, TextRpg_MonsterHunting/Quest.cs, TextRpg_MonsterHunting/QuestManager.cs
=> [Update] Quest,Quest Manager

TextRpg_MonsterHunting/Character/Character.cs, TextRpg_MonsterHunting/Dungeon.cs
=> [Update] 캐릭터 처음 생성시 스테이지 초기화

TextRpg_MonsterHunting/Dungeon.cs
전투 씬,
필요 객체들,
전투 종료 확인,
전투 씬 중 데미지 계산 추가
=> [Feature] 전투씬 추가

TextRpg_MonsterHunting/Character/Character.cs, TextRpg_MonsterHunting/Dungeon.cs
캐릭터에 skillManager public으로 변경
던전에 전투(공격하면 출력, 맞으면 출력) 기능 완료
던전 종료 후 보상, 승패 처리 기능 추가
=> [Features][Update] 던전 기능 추가, 캐릭터 약간수정

TextRpg_MonsterHunting/Inventory.cs
굳이 character.inventory 로 접근하지 않아도 되는 부분 수정
하였으나 더욱 간결한 코드로 대체
=> [Refactor] 코드 간결화 작업

TextRpg_MonsterHunting/Scene/IntroScene.cs, TextRpg_MonsterHunting/Scene/StartScene.cs, TextRpg_MonsterHunting/Utils.cs
저장, 불러오기, 저장 초기화 함수는 Utils에 추가
영웅은 intro에서 불러오고 불러올 경우 출력 창 달라짐
startscene에서 저장함
=> [Feature][Update] 영웅 저장, 불러오기, 저장초기화 기능추가

TextRpg_MonsterHunting/Character/Character.cs, TextRpg_MonsterHunting/Item.cs, TextRpg_MonsterHunting/Scene/StartScene.cs, TextRpg_MonsterHunting/Shop.cs, TextRpg_MonsterHunting/Utils.cs
샵 추가하고 관련 기능 수정중
캐릭터 클래스 json 생성자 제작
item에 가격 추가
Utils에 상점 저장, 불러오기 추가
스타트 씬에 상점 입장 선택지 추가 중
=> [Update][Add] 샵추가, 다른 파일 수정

TextRpg_MonsterHunting/Item.cs, TextRpg_MonsterHunting/Shop.cs, TextRpg_MonsterHunting/Utils.cs
상점 저장은 아직 미지정. 저장 관련 함수만 구현
아이템에 아이템 타입 string값으로 주는 함수 추가
상점 구매, 판매, 상점화면 추가
=> [Feature] 상점 기능 완료

TextRpg_MonsterHunting/Character/Archer.cs, TextRpg_MonsterHunting/Character/Character.cs, TextRpg_MonsterHunting/Character/Warrior.cs, TextRpg_MonsterHunting/Character/Wizard.cs, TextRpg_MonsterHunting/Dungeon.cs, TextRpg_MonsterHunting/Game.cs, TextRpg_MonsterHunting/Inventory.cs, TextRpg_MonsterHunting/Item.cs, TextRpg_MonsterHunting/Monster.cs, TextRpg_MonsterHunting/Scene/EquipmentScene.cs, TextRpg_MonsterHunting/Scene/InventoryScene.cs, TextRpg_MonsterHunting/Scene/PotionScene.cs, TextRpg_MonsterHunting/Scene/StartScene.cs, TextRpg_MonsterHunting/Shop.cs, TextRpg_MonsterHunting/Skill/SkillManager.cs, TextRpg_MonsterHunting/Utils.cs
=> [Fix] 버그 많이 수정

TextRpg_MonsterHunting/Character/Character.cs, TextRpg_MonsterHunting/Shop.cs, TextRpg_MonsterHunting/Utils.cs
캐릭터 상태창에 마나 보기 추가
샵에 아이템 리스트 인터페이스에서 EquipmentList 클래스로 클래스 변경
=> [Update] 캐릭터, 샵 수정

TextRpg_MonsterHunting/Shop.cs
=> [Update] 상점으로 이동시 클리어

TextRpg_MonsterHunting/Quest/Quest.cs, TextRpg_MonsterHunting/Quest/QuestManager.cs, TextRpg_MonsterHunting/Scene/CharacterInfoScene.cs, TextRpg_MonsterHunting/Scene/EquipmentScene.cs, TextRpg_MonsterHunting/Scene/InventoryScene.cs, TextRpg_MonsterHunting/Scene/PotionScene.cs, TextRpg_MonsterHunting/Scene/QuestAcceptanceScene.cs, TextRpg_MonsterHunting/Scene/QuestScene.cs, TextRpg_MonsterHunting/Scene/StartScene.cs
1. QuestAcceptScene 을 QuestScene 에 병합
2. StartScene에 퀘스트 보기 추가
2. 불필요한 Console.Clear(); 제거
=> [Fix] QuestAcceptScene 을 QuestScene 에 병합

TextRpg_MonsterHunting/Character/Character.cs, TextRpg_MonsterHunting/Dungeon.cs, TextRpg_MonsterHunting/Inventory.cs, TextRpg_MonsterHunting/Shop.cs, TextRpg_MonsterHunting/Utils.cs
캐릭터 생성자, 포션 사용등에 있던 버그들 수정하고
던전 보상템 가격등 수치 변경
=> [Complex] 버그 수정, 몇가지 수치 변경
